######################################################################
#
# File name : local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_example_top_sim_compile.do
# Created on: Sat May 20 09:39:00 CST 2017
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/gtwizard_ultrascale_v1_6_5
vlib msim/xil_defaultlib

vmap gtwizard_ultrascale_v1_6_5 msim/gtwizard_ultrascale_v1_6_5
vmap xil_defaultlib msim/xil_defaultlib

vlog -64 -incr -work gtwizard_ultrascale_v1_6_5  "+incdir+../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/imports" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_6_bit_sync.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_6_gthe3_cpll_cal.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_6_gthe3_cal_freqcnt.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_6_gthe4_cpll_cal.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_6_gthe4_cal_freqcnt.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_6_gtye4_cpll_cal.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_6_gtye4_cal_freqcnt.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_6_gtwiz_buffbypass_rx.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_6_gtwiz_buffbypass_tx.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_6_gtwiz_reset.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_6_gtwiz_userclk_rx.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_6_gtwiz_userclk_tx.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_6_gtwiz_userdata_rx.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_6_gtwiz_userdata_tx.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_6_reset_sync.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_6_reset_inv_sync.v" \

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/imports" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.srcs/sources_1/ip/gtwizard_ultrascale_0/sim/gtwizard_ultrascale_v1_6_gtye4_channel.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.srcs/sources_1/ip/gtwizard_ultrascale_0/sim/gtwizard_ultrascale_0_gtye4_channel_wrapper.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.srcs/sources_1/ip/gtwizard_ultrascale_0/sim/gtwizard_ultrascale_v1_6_gtye4_common.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.srcs/sources_1/ip/gtwizard_ultrascale_0/sim/gtwizard_ultrascale_0_gtye4_common_wrapper.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.srcs/sources_1/ip/gtwizard_ultrascale_0/sim/gtwizard_ultrascale_0_gtwizard_gtye4.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.srcs/sources_1/ip/gtwizard_ultrascale_0/sim/gtwizard_ultrascale_0_gtwizard_top.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.srcs/sources_1/ip/gtwizard_ultrascale_0/sim/gtwizard_ultrascale_0.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_bit_sync.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_gtwiz_userclk_rx.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_gtwiz_userclk_tx.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_reset_sync.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_prbs_any.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_checking_raw.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_init.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_stimulus_raw.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_wrapper.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.srcs/sources_1/ip/gtwizard_ultrascale_0_vio_0/sim/gtwizard_ultrascale_0_vio_0.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_top.v" \
"../../../local_project/PCIE_serdes_clk/PCIE_serdes_clk/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_top_sim.v" \

# compile glbl module
vlog -work work "glbl.v"

