#!/bin/sh -f
# ****************************************************************************
# Vivado (TM) v2017.3 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Fri Oct 18 17:27:30 CST 2019
# SW Build 2018833 on Wed Oct  4 19:58:07 MDT 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
UVM_HOME=/home/wangguobin/project/TSN/verfication/tsn/VER/common/uvm-1.1b
# installation path setting
bin_path="/usr/synopsys/L-2016.06/bin"

# directory path for design sources and include directories (if any) wrt this path
origin_dir="."

# set vhdlan command line args
vhdlan_opts="-full64"

# set vlogan command line args
vlogan_opts="-full64"

vlogan_define="SIM"

# compile glbl module
$bin_path/vlogan $vlogan_opts   +define+$vlogan_define +v2k -sverilog -work xil_defaultlib -f dut_filelist.f -f filelist_hw_engine.f 2>&1 | tee -a vlogan.log

$bin_path/vlogan $vlogan_opts +define+$vlogan_define -sverilog -work xil_defaultlib +define+SVT_UVM_TECHNOLOGY \
	+define+SYNOPSYS_SV  \
	+define+UVM_PACKER_MAX_BYTES=1500000 \
	+define+UVM_DISABLE_AUTO_ITEM_RECORDING \
	+incdir+${UVM_HOME}/src \
	${UVM_HOME}/src/dpi/uvm_dpi.cc \
    ${UVM_HOME}/src/uvm_pkg.sv \
	-timescale=1ns/1ps \
    -f env_filelist.f  2>&1 | tee -a vlogan.log
