######################################################################
#
# File name : gtwizard_ultrascale_0_example_top_sim_simulate.do
# Created on: Sat May 20 09:39:02 CST 2017
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L gtwizard_ultrascale_v1_6_5 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.gtwizard_ultrascale_0_example_top_sim xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {gtwizard_ultrascale_0_example_top_sim_wave.do}

view wave
view structure
view signals

do {gtwizard_ultrascale_0_example_top_sim.udo}

run 1000ns
