library verilog;
use verilog.vl_types.all;
entity gtwizard_ultrascale_v1_6_5_gtye4_common is
    generic(
        GTYE4_COMMON_AEN_QPLL0_FBDIV: vl_logic_vector(0 downto 0) := (others => Hi1);
        GTYE4_COMMON_AEN_QPLL1_FBDIV: vl_logic_vector(0 downto 0) := (others => Hi1);
        GTYE4_COMMON_AEN_SDM0TOGGLE: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_AEN_SDM1TOGGLE: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_A_SDM0TOGGLE: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_A_SDM1DATA_HIGH: vl_logic_vector(8 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_A_SDM1DATA_LOW: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_A_SDM1TOGGLE: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_BIAS_CFG0: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_BIAS_CFG1: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_BIAS_CFG2: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_BIAS_CFG3: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_BIAS_CFG4: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_BIAS_CFG_RSVD: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_COMMON_CFG0: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_COMMON_CFG1: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_POR_CFG: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_PPF0_CFG: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi1, Hi1, Hi1, Hi1, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_PPF1_CFG: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi1, Hi1, Hi1, Hi1, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL0CLKOUT_RATE: string  := "FULL";
        GTYE4_COMMON_QPLL0_CFG0: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi1, Hi1, Hi1, Hi0, Hi0, Hi1, Hi0, Hi0, Hi0, Hi1, Hi1, Hi1, Hi0, Hi0);
        GTYE4_COMMON_QPLL0_CFG1: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL0_CFG1_G3: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi1, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL0_CFG2: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi1, Hi1, Hi1, Hi1, Hi1, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL0_CFG2_G3: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi1, Hi1, Hi1, Hi1, Hi1, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL0_CFG3: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi1, Hi0, Hi0, Hi1, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL0_CFG4: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi1, Hi0);
        GTYE4_COMMON_QPLL0_CP: vl_logic_vector(9 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi1, Hi1, Hi1, Hi1, Hi1);
        GTYE4_COMMON_QPLL0_CP_G3: vl_logic_vector(9 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi1, Hi1, Hi1, Hi1, Hi1);
        GTYE4_COMMON_QPLL0_FBDIV: integer := 66;
        GTYE4_COMMON_QPLL0_FBDIV_G3: integer := 80;
        GTYE4_COMMON_QPLL0_INIT_CFG0: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL0_INIT_CFG1: vl_logic_vector(7 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL0_LOCK_CFG: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi1, Hi1, Hi1, Hi1, Hi0, Hi1, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL0_LOCK_CFG_G3: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi1, Hi0, Hi0, Hi0, Hi0, Hi1, Hi1, Hi1, Hi1, Hi0, Hi1, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL0_LPF: vl_logic_vector(9 downto 0) := (Hi1, Hi0, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1);
        GTYE4_COMMON_QPLL0_LPF_G3: vl_logic_vector(9 downto 0) := (Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1);
        GTYE4_COMMON_QPLL0_PCI_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL0_RATE_SW_USE_DRP: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL0_REFCLK_DIV: integer := 1;
        GTYE4_COMMON_QPLL0_SDM_CFG0: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi1, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL0_SDM_CFG1: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL0_SDM_CFG2: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL1CLKOUT_RATE: string  := "FULL";
        GTYE4_COMMON_QPLL1_CFG0: vl_logic_vector(15 downto 0) := (Hi0, Hi1, Hi1, Hi0, Hi1, Hi0, Hi0, Hi1, Hi0, Hi0, Hi0, Hi1, Hi1, Hi1, Hi0, Hi0);
        GTYE4_COMMON_QPLL1_CFG1: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi1, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL1_CFG1_G3: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi1, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL1_CFG2: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi1, Hi1, Hi1, Hi1, Hi1, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL1_CFG2_G3: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi1, Hi1, Hi1, Hi1, Hi1, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL1_CFG3: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi1, Hi0, Hi0, Hi1, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL1_CFG4: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi1, Hi0);
        GTYE4_COMMON_QPLL1_CP: vl_logic_vector(9 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi1, Hi1, Hi1, Hi1, Hi1);
        GTYE4_COMMON_QPLL1_CP_G3: vl_logic_vector(9 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi1, Hi1, Hi1, Hi1, Hi1);
        GTYE4_COMMON_QPLL1_FBDIV: integer := 66;
        GTYE4_COMMON_QPLL1_FBDIV_G3: integer := 80;
        GTYE4_COMMON_QPLL1_INIT_CFG0: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL1_INIT_CFG1: vl_logic_vector(7 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL1_LOCK_CFG: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi1, Hi1, Hi1, Hi1, Hi0, Hi1, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL1_LOCK_CFG_G3: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi1, Hi0, Hi0, Hi0, Hi0, Hi1, Hi1, Hi1, Hi1, Hi0, Hi1, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL1_LPF: vl_logic_vector(9 downto 0) := (Hi1, Hi0, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1);
        GTYE4_COMMON_QPLL1_LPF_G3: vl_logic_vector(9 downto 0) := (Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1, Hi1);
        GTYE4_COMMON_QPLL1_PCI_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL1_RATE_SW_USE_DRP: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL1_REFCLK_DIV: integer := 1;
        GTYE4_COMMON_QPLL1_SDM_CFG0: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL1_SDM_CFG1: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL1_SDM_CFG2: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_RSVD_ATTR0: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_RSVD_ATTR1: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_RSVD_ATTR2: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_RSVD_ATTR3: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_RXRECCLKOUT0_SEL: vl_logic_vector(1 downto 0) := (Hi0, Hi0);
        GTYE4_COMMON_RXRECCLKOUT1_SEL: vl_logic_vector(1 downto 0) := (Hi0, Hi0);
        GTYE4_COMMON_SARC_ENB: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_SARC_SEL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_SDM0INITSEED0_0: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_SDM0INITSEED0_1: vl_logic_vector(8 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_SDM1INITSEED0_0: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_SDM1INITSEED0_1: vl_logic_vector(8 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_SIM_MODE: string  := "FAST";
        GTYE4_COMMON_SIM_RESET_SPEEDUP: string  := "TRUE";
        GTYE4_COMMON_SIM_DEVICE: string  := "ULTRASCALE_PLUS";
        GTYE4_COMMON_UB_CFG0: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_UB_CFG1: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_UB_CFG2: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_UB_CFG3: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_UB_CFG4: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_UB_CFG5: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi1, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_UB_CFG6: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_BGBYPASSB_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_BGMONITORENB_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_BGPDB_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_BGRCALOVRD_VAL: vl_logic_vector(4 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_BGRCALOVRDENB_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_DRPADDR_VAL: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_DRPCLK_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_DRPDI_VAL: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_DRPEN_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_DRPWE_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTGREFCLK0_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTGREFCLK1_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTNORTHREFCLK00_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTNORTHREFCLK01_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTNORTHREFCLK10_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTNORTHREFCLK11_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTREFCLK00_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTREFCLK01_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTREFCLK10_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTREFCLK11_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTSOUTHREFCLK00_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTSOUTHREFCLK01_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTSOUTHREFCLK10_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTSOUTHREFCLK11_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_PCIERATEQPLL0_VAL: vl_logic_vector(2 downto 0) := (Hi0, Hi0, Hi0);
        GTYE4_COMMON_PCIERATEQPLL1_VAL: vl_logic_vector(2 downto 0) := (Hi0, Hi0, Hi0);
        GTYE4_COMMON_PMARSVD0_VAL: vl_logic_vector(7 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_PMARSVD1_VAL: vl_logic_vector(7 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL0CLKRSVD0_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL0CLKRSVD1_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL0FBDIV_VAL: vl_logic_vector(7 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL0LOCKDETCLK_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL0LOCKEN_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL0PD_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL0REFCLKSEL_VAL: vl_logic_vector(2 downto 0) := (Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL0RESET_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL1CLKRSVD0_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL1CLKRSVD1_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL1FBDIV_VAL: vl_logic_vector(7 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL1LOCKDETCLK_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL1LOCKEN_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL1PD_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL1REFCLKSEL_VAL: vl_logic_vector(2 downto 0) := (Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLL1RESET_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLLRSVD1_VAL: vl_logic_vector(7 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLLRSVD2_VAL: vl_logic_vector(4 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLLRSVD3_VAL: vl_logic_vector(4 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_QPLLRSVD4_VAL: vl_logic_vector(7 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_RCALENB_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_SDM0DATA_VAL: vl_logic_vector(24 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_SDM0RESET_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_SDM0TOGGLE_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_SDM0WIDTH_VAL: vl_logic_vector(1 downto 0) := (Hi0, Hi0);
        GTYE4_COMMON_SDM1DATA_VAL: vl_logic_vector(24 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_SDM1RESET_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_SDM1TOGGLE_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_SDM1WIDTH_VAL: vl_logic_vector(1 downto 0) := (Hi0, Hi0);
        GTYE4_COMMON_UBCFGSTREAMEN_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBDO_VAL: vl_logic_vector(15 downto 0) := (Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_UBDRDY_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBENABLE_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBGPI_VAL: vl_logic_vector(1 downto 0) := (Hi0, Hi0);
        GTYE4_COMMON_UBINTR_VAL: vl_logic_vector(1 downto 0) := (Hi0, Hi0);
        GTYE4_COMMON_UBIOLMBRST_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBMBRST_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBMDMCAPTURE_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBMDMDBGRST_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBMDMDBGUPDATE_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBMDMREGEN_VAL: vl_logic_vector(3 downto 0) := (Hi0, Hi0, Hi0, Hi0);
        GTYE4_COMMON_UBMDMSHIFT_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBMDMSYSRST_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBMDMTCK_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBMDMTDI_VAL: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_BGBYPASSB_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_BGMONITORENB_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_BGPDB_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_BGRCALOVRD_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_BGRCALOVRDENB_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_DRPADDR_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_DRPCLK_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_DRPDI_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_DRPEN_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_DRPWE_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTGREFCLK0_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTGREFCLK1_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTNORTHREFCLK00_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTNORTHREFCLK01_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTNORTHREFCLK10_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTNORTHREFCLK11_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTREFCLK00_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTREFCLK01_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTREFCLK10_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTREFCLK11_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTSOUTHREFCLK00_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTSOUTHREFCLK01_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTSOUTHREFCLK10_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_GTSOUTHREFCLK11_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_PCIERATEQPLL0_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_PCIERATEQPLL1_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_PMARSVD0_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_PMARSVD1_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL0CLKRSVD0_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL0CLKRSVD1_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL0FBDIV_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL0LOCKDETCLK_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL0LOCKEN_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL0PD_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL0REFCLKSEL_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL0RESET_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL1CLKRSVD0_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL1CLKRSVD1_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL1FBDIV_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL1LOCKDETCLK_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL1LOCKEN_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL1PD_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL1REFCLKSEL_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLL1RESET_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLLRSVD1_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLLRSVD2_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLLRSVD3_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_QPLLRSVD4_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_RCALENB_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_SDM0DATA_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_SDM0RESET_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_SDM0TOGGLE_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_SDM0WIDTH_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_SDM1DATA_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_SDM1RESET_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_SDM1TOGGLE_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_SDM1WIDTH_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBCFGSTREAMEN_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBDO_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBDRDY_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBENABLE_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBGPI_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBINTR_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBIOLMBRST_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBMBRST_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBMDMCAPTURE_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBMDMDBGRST_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBMDMDBGUPDATE_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBMDMREGEN_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBMDMSHIFT_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBMDMSYSRST_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBMDMTCK_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0);
        GTYE4_COMMON_UBMDMTDI_TIE_EN: vl_logic_vector(0 downto 0) := (others => Hi0)
    );
    port(
        GTYE4_COMMON_BGBYPASSB: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_BGMONITORENB: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_BGPDB: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_BGRCALOVRD: in     vl_logic_vector(4 downto 0);
        GTYE4_COMMON_BGRCALOVRDENB: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_DRPADDR: in     vl_logic_vector(15 downto 0);
        GTYE4_COMMON_DRPCLK: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_DRPDI: in     vl_logic_vector(15 downto 0);
        GTYE4_COMMON_DRPEN: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_DRPWE: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_GTGREFCLK0: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_GTGREFCLK1: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_GTNORTHREFCLK00: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_GTNORTHREFCLK01: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_GTNORTHREFCLK10: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_GTNORTHREFCLK11: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_GTREFCLK00: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_GTREFCLK01: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_GTREFCLK10: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_GTREFCLK11: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_GTSOUTHREFCLK00: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_GTSOUTHREFCLK01: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_GTSOUTHREFCLK10: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_GTSOUTHREFCLK11: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_PCIERATEQPLL0: in     vl_logic_vector(2 downto 0);
        GTYE4_COMMON_PCIERATEQPLL1: in     vl_logic_vector(2 downto 0);
        GTYE4_COMMON_PMARSVD0: in     vl_logic_vector(7 downto 0);
        GTYE4_COMMON_PMARSVD1: in     vl_logic_vector(7 downto 0);
        GTYE4_COMMON_QPLL0CLKRSVD0: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLL0CLKRSVD1: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLL0FBDIV: in     vl_logic_vector(7 downto 0);
        GTYE4_COMMON_QPLL0LOCKDETCLK: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLL0LOCKEN: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLL0PD: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLL0REFCLKSEL: in     vl_logic_vector(2 downto 0);
        GTYE4_COMMON_QPLL0RESET: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLL1CLKRSVD0: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLL1CLKRSVD1: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLL1FBDIV: in     vl_logic_vector(7 downto 0);
        GTYE4_COMMON_QPLL1LOCKDETCLK: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLL1LOCKEN: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLL1PD: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLL1REFCLKSEL: in     vl_logic_vector(2 downto 0);
        GTYE4_COMMON_QPLL1RESET: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLLRSVD1: in     vl_logic_vector(7 downto 0);
        GTYE4_COMMON_QPLLRSVD2: in     vl_logic_vector(4 downto 0);
        GTYE4_COMMON_QPLLRSVD3: in     vl_logic_vector(4 downto 0);
        GTYE4_COMMON_QPLLRSVD4: in     vl_logic_vector(7 downto 0);
        GTYE4_COMMON_RCALENB: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_SDM0DATA: in     vl_logic_vector(24 downto 0);
        GTYE4_COMMON_SDM0RESET: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_SDM0TOGGLE: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_SDM0WIDTH: in     vl_logic_vector(1 downto 0);
        GTYE4_COMMON_SDM1DATA: in     vl_logic_vector(24 downto 0);
        GTYE4_COMMON_SDM1RESET: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_SDM1TOGGLE: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_SDM1WIDTH: in     vl_logic_vector(1 downto 0);
        GTYE4_COMMON_UBCFGSTREAMEN: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_UBDO: in     vl_logic_vector(15 downto 0);
        GTYE4_COMMON_UBDRDY: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_UBENABLE: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_UBGPI: in     vl_logic_vector(1 downto 0);
        GTYE4_COMMON_UBINTR: in     vl_logic_vector(1 downto 0);
        GTYE4_COMMON_UBIOLMBRST: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_UBMBRST: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_UBMDMCAPTURE: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_UBMDMDBGRST: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_UBMDMDBGUPDATE: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_UBMDMREGEN: in     vl_logic_vector(3 downto 0);
        GTYE4_COMMON_UBMDMSHIFT: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_UBMDMSYSRST: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_UBMDMTCK: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_UBMDMTDI: in     vl_logic_vector(0 downto 0);
        GTYE4_COMMON_DRPDO: out    vl_logic_vector(15 downto 0);
        GTYE4_COMMON_DRPRDY: out    vl_logic_vector(0 downto 0);
        GTYE4_COMMON_PMARSVDOUT0: out    vl_logic_vector(7 downto 0);
        GTYE4_COMMON_PMARSVDOUT1: out    vl_logic_vector(7 downto 0);
        GTYE4_COMMON_QPLL0FBCLKLOST: out    vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLL0LOCK: out    vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLL0OUTCLK: out    vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLL0OUTREFCLK: out    vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLL0REFCLKLOST: out    vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLL1FBCLKLOST: out    vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLL1LOCK: out    vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLL1OUTCLK: out    vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLL1OUTREFCLK: out    vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLL1REFCLKLOST: out    vl_logic_vector(0 downto 0);
        GTYE4_COMMON_QPLLDMONITOR0: out    vl_logic_vector(7 downto 0);
        GTYE4_COMMON_QPLLDMONITOR1: out    vl_logic_vector(7 downto 0);
        GTYE4_COMMON_REFCLKOUTMONITOR0: out    vl_logic_vector(0 downto 0);
        GTYE4_COMMON_REFCLKOUTMONITOR1: out    vl_logic_vector(0 downto 0);
        GTYE4_COMMON_RXRECCLK0SEL: out    vl_logic_vector(1 downto 0);
        GTYE4_COMMON_RXRECCLK1SEL: out    vl_logic_vector(1 downto 0);
        GTYE4_COMMON_SDM0FINALOUT: out    vl_logic_vector(3 downto 0);
        GTYE4_COMMON_SDM0TESTDATA: out    vl_logic_vector(14 downto 0);
        GTYE4_COMMON_SDM1FINALOUT: out    vl_logic_vector(3 downto 0);
        GTYE4_COMMON_SDM1TESTDATA: out    vl_logic_vector(14 downto 0);
        GTYE4_COMMON_UBDADDR: out    vl_logic_vector(15 downto 0);
        GTYE4_COMMON_UBDEN: out    vl_logic_vector(0 downto 0);
        GTYE4_COMMON_UBDI: out    vl_logic_vector(15 downto 0);
        GTYE4_COMMON_UBDWE: out    vl_logic_vector(0 downto 0);
        GTYE4_COMMON_UBMDMTDO: out    vl_logic_vector(0 downto 0);
        GTYE4_COMMON_UBRSVDOUT: out    vl_logic_vector(0 downto 0);
        GTYE4_COMMON_UBTXUART: out    vl_logic_vector(0 downto 0)
    );
    attribute mti_svvh_generic_type : integer;
    attribute mti_svvh_generic_type of GTYE4_COMMON_AEN_QPLL0_FBDIV : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_AEN_QPLL1_FBDIV : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_AEN_SDM0TOGGLE : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_AEN_SDM1TOGGLE : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_A_SDM0TOGGLE : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_A_SDM1DATA_HIGH : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_A_SDM1DATA_LOW : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_A_SDM1TOGGLE : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_BIAS_CFG0 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_BIAS_CFG1 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_BIAS_CFG2 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_BIAS_CFG3 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_BIAS_CFG4 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_BIAS_CFG_RSVD : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_COMMON_CFG0 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_COMMON_CFG1 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_POR_CFG : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_PPF0_CFG : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_PPF1_CFG : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0CLKOUT_RATE : constant is 1;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_CFG0 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_CFG1 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_CFG1_G3 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_CFG2 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_CFG2_G3 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_CFG3 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_CFG4 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_CP : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_CP_G3 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_FBDIV : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_FBDIV_G3 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_INIT_CFG0 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_INIT_CFG1 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_LOCK_CFG : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_LOCK_CFG_G3 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_LPF : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_LPF_G3 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_PCI_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_RATE_SW_USE_DRP : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_REFCLK_DIV : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_SDM_CFG0 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_SDM_CFG1 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0_SDM_CFG2 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1CLKOUT_RATE : constant is 1;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_CFG0 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_CFG1 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_CFG1_G3 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_CFG2 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_CFG2_G3 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_CFG3 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_CFG4 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_CP : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_CP_G3 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_FBDIV : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_FBDIV_G3 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_INIT_CFG0 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_INIT_CFG1 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_LOCK_CFG : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_LOCK_CFG_G3 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_LPF : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_LPF_G3 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_PCI_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_RATE_SW_USE_DRP : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_REFCLK_DIV : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_SDM_CFG0 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_SDM_CFG1 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1_SDM_CFG2 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_RSVD_ATTR0 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_RSVD_ATTR1 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_RSVD_ATTR2 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_RSVD_ATTR3 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_RXRECCLKOUT0_SEL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_RXRECCLKOUT1_SEL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SARC_ENB : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SARC_SEL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SDM0INITSEED0_0 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SDM0INITSEED0_1 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SDM1INITSEED0_0 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SDM1INITSEED0_1 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SIM_MODE : constant is 1;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SIM_RESET_SPEEDUP : constant is 1;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SIM_DEVICE : constant is 1;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UB_CFG0 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UB_CFG1 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UB_CFG2 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UB_CFG3 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UB_CFG4 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UB_CFG5 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UB_CFG6 : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_BGBYPASSB_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_BGMONITORENB_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_BGPDB_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_BGRCALOVRD_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_BGRCALOVRDENB_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_DRPADDR_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_DRPCLK_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_DRPDI_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_DRPEN_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_DRPWE_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTGREFCLK0_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTGREFCLK1_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTNORTHREFCLK00_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTNORTHREFCLK01_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTNORTHREFCLK10_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTNORTHREFCLK11_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTREFCLK00_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTREFCLK01_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTREFCLK10_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTREFCLK11_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTSOUTHREFCLK00_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTSOUTHREFCLK01_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTSOUTHREFCLK10_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTSOUTHREFCLK11_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_PCIERATEQPLL0_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_PCIERATEQPLL1_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_PMARSVD0_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_PMARSVD1_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0CLKRSVD0_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0CLKRSVD1_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0FBDIV_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0LOCKDETCLK_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0LOCKEN_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0PD_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0REFCLKSEL_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0RESET_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1CLKRSVD0_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1CLKRSVD1_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1FBDIV_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1LOCKDETCLK_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1LOCKEN_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1PD_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1REFCLKSEL_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1RESET_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLLRSVD1_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLLRSVD2_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLLRSVD3_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLLRSVD4_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_RCALENB_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SDM0DATA_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SDM0RESET_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SDM0TOGGLE_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SDM0WIDTH_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SDM1DATA_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SDM1RESET_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SDM1TOGGLE_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SDM1WIDTH_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBCFGSTREAMEN_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBDO_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBDRDY_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBENABLE_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBGPI_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBINTR_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBIOLMBRST_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBMBRST_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBMDMCAPTURE_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBMDMDBGRST_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBMDMDBGUPDATE_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBMDMREGEN_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBMDMSHIFT_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBMDMSYSRST_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBMDMTCK_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBMDMTDI_VAL : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_BGBYPASSB_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_BGMONITORENB_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_BGPDB_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_BGRCALOVRD_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_BGRCALOVRDENB_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_DRPADDR_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_DRPCLK_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_DRPDI_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_DRPEN_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_DRPWE_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTGREFCLK0_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTGREFCLK1_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTNORTHREFCLK00_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTNORTHREFCLK01_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTNORTHREFCLK10_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTNORTHREFCLK11_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTREFCLK00_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTREFCLK01_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTREFCLK10_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTREFCLK11_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTSOUTHREFCLK00_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTSOUTHREFCLK01_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTSOUTHREFCLK10_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_GTSOUTHREFCLK11_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_PCIERATEQPLL0_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_PCIERATEQPLL1_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_PMARSVD0_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_PMARSVD1_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0CLKRSVD0_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0CLKRSVD1_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0FBDIV_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0LOCKDETCLK_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0LOCKEN_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0PD_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0REFCLKSEL_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL0RESET_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1CLKRSVD0_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1CLKRSVD1_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1FBDIV_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1LOCKDETCLK_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1LOCKEN_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1PD_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1REFCLKSEL_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLL1RESET_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLLRSVD1_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLLRSVD2_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLLRSVD3_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_QPLLRSVD4_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_RCALENB_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SDM0DATA_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SDM0RESET_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SDM0TOGGLE_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SDM0WIDTH_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SDM1DATA_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SDM1RESET_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SDM1TOGGLE_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_SDM1WIDTH_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBCFGSTREAMEN_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBDO_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBDRDY_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBENABLE_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBGPI_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBINTR_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBIOLMBRST_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBMBRST_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBMDMCAPTURE_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBMDMDBGRST_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBMDMDBGUPDATE_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBMDMREGEN_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBMDMSHIFT_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBMDMSYSRST_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBMDMTCK_TIE_EN : constant is 2;
    attribute mti_svvh_generic_type of GTYE4_COMMON_UBMDMTDI_TIE_EN : constant is 2;
end gtwizard_ultrascale_v1_6_5_gtye4_common;
