#!/bin/sh -f
# ****************************************************************************
# Vivado (TM) v2017.3 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Oct 18 17:27:31 CST 2019
# SW Build 2018833 on Wed Oct  4 19:58:07 MDT 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
UVM_HOME=/home/wangguobin/project/TSN/verfication/tsn/VER/common/uvm-1.1b
VERDI_PATH=/usr/synopsys/Verdi3_L-2016.06-1/share/PLI/VCS/LINUX64
# installation path setting
bin_path="/usr/synopsys/L-2016.06/bin"

# set vcs command line args
vcs_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"

# run elaboration
#$bin_path/vcs $vcs_opts xil_defaultlib.fifo_generator_0_tb xil_defaultlib.glbl -o fifo_generator_0_tb_simv
#$bin_path/vcs $vcs_opts xil_defaultlib.tsn_sw_top  xil_defaultlib.glbl -o fifo_generator_0_tb_simv

vcs -full64  \
    xil_defaultlib.pcs_tb_top xil_defaultlib.glbl \
	+vpi \
	-timescale=1ns/1ps \
	-debug_access+all \
	${UVM_HOME}/src/dpi/uvm_dpi.cc \
	+error+10 \
	-P ${VERDI_PATH}/novas.tab \
        ${VERDI_PATH}/pli.a \
	-l comp.log -CFLAGS -DVCS 
